Make it explicit that libiscsi needs to be version 1.13 at least.
Previous versions would fail to import the module with the error:

    ImportError: /home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/iscsi.cpython-35m-x86_64-linux-gnu.so: undefined symbol: scsi_task_get_status